apiVersion: v1
kind: Service
metadata:
  name: tetrisserver-service
spec:
  selector:
    app: tetrisserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080    # Specify a static port for NodePort
  type: NodePort        # Change the service type to NodePort