apiVersion: v1
kind: Service
metadata:
  name: tetrisserver-service
  labels:
    app: tetrisserver
spec:
  selector:
    app: tetrisserver  # Must match the labels on your Deployment's pods
  ports:
    - protocol: TCP
      nodePort: 32481
      port: 8080  # The port that the service will expose
      targetPort: 8080  # The port that the API is running on inside the pod
  type: NodePort